AllCops:
  NewCops: enable
  SuggestExtensions: false

# Allow longer methods for Lambda handlers and complex authentication logic
Metrics/MethodLength:
  Max: 50
  AllowedMethods: ['lambda_handler', 'authenticate', 'validate_token', 'retrieve_secret', 'authentication_error_response']

# Allow higher complexity for Lambda handlers and core business logic
Metrics/AbcSize:
  Max: 75

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

# Allow larger classes for core functionality
Metrics/ClassLength:
  Max: 150

# Allow more parameters for webhook and notification methods
Metrics/ParameterLists:
  Max: 6

# Allow longer blocks in spec files (RSpec tests often need longer describe/context blocks)
Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'

# Allow long lines in specs with test data
Layout/LineLength:
  Max: 120
  AllowedPatterns: ['^\s*#']
  Exclude:
    - 'spec/**/*'

# Allow missing documentation for simple classes like authenticators
Style/Documentation:
  Enabled: false

# Allow unused context parameter in Lambda handlers (required by AWS Lambda)
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

# Disable FetchEnvVar for ENV variable checks in specs and app code
Style/FetchEnvVar:
  Enabled: false