# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 3.4'

# Testing
group :test do
  gem 'rspec', '~> 3.12'
end

# JSON handling
gem 'json'

# JWT authentication
gem 'jwt', '~> 2.7'

# AWS SDK for Secrets Manager
gem 'aws-sdk-secretsmanager', '~> 1'

gem 'rubocop', '~> 1.81'
