source "https://rubygems.org"

gem "httparty"
gem "ruby-vips", "~> 2.2"
gem "jwt", "~> 2.7"
gem "aws-sdk-secretsmanager", "~> 1.97"
gem "aws-sdk-cloudwatch", "~> 1.97"
gem "aws-sdk-s3", "~> 1.165"
gem "concurrent-ruby", "~> 1.2"
gem "net-http"
gem "uri"
gem "json"
gem "tempfile"

ruby '~> 3.4'
