# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "content_processing"

[default.build.parameters]
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
resolve_image_repos = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# LocalStack configuration
[localstack.global.parameters]
stack_name = "pdf-processor-local"

[localstack.build.parameters]
parallel = true

[localstack.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = false
parameter_overrides = "JWTSecretValue=localstack-secret-key"

[localstack.local_start_api.parameters]
warm_containers = "EAGER"
docker_network = "content_processing_localstack-net"
host = "0.0.0.0"

[localstack.local_start_lambda.parameters]
warm_containers = "EAGER"
docker_network = "content_processing_localstack-net"
